= Spring Integration Adapter for Apache Kafka

image::https://build.spring.io/plugins/servlet/buildStatusImage/INTEXT-KAFKA[]

The *Spring Integration for Apache Kafka* extension project provides inbound and outbound channel adapters and gateways for Apache Kafka.
Apache Kafka is a distributed publish-subscribe messaging system that is designed for high throughput (terabytes of data) and low latency (milliseconds).
For more information on Kafka and its design goals, see the http://kafka.apache.org/[Kafka main page].

Starting from _version 2.0_ version this project is a complete rewrite based on the new
https://github.com/spring-projects/spring-kafka[spring-kafka] project which uses the pure java "new" `Producer` and
`Consumer` clients provided by Kafka.

== Quick Start

See the
https://github.com/spring-projects/spring-integration-samples/tree/master/basic/kafka[Spring Integration kafka Sample] for a simple Spring Boot application that sends and receives messages.

== Checking out and building

In order to build the project:

    ./gradlew build

In order to install this into your local maven cache:

    ./gradlew install

== Documentation

Documentation for this extension is contained in a chapter of the https://docs.spring.io/spring-kafka/reference/html/#spring-integration[Spring for Apache Kafka Reference Manual]

== Migrating from 3.0 to 3.1

Producer record metadata for sends performed on the outbound channel adapter are now sent only to the `successChannel`.
With earlier versions, it was sent to the `outputChannel` if no `successChannel` was provided.

== Contributing

http://help.github.com/send-pull-requests[Pull requests] are welcome. Please see the https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc[contributor guidelines] for details.
